export const PRODUCTS = 'products';
export const SELECTED_PRODUCT = 'selectedProduct';
export const ADDED_TO_CART = 'addedToCart';
export const REMOVED_FROM_CART = 'removedFromCart';
export const ADDED_QTY = 'addedQty'
export const SUB_QTY = 'subQty';
export const CHANGE_QTY ='changeQty';
export const FETCH_PRODUCTS = 'fetchProducts';
export const FILTER = 'filter';